# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        #self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setGeometry(QtCore.QRect(480, 10, 421, 281))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.lineEdit_Treatment = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Treatment.setObjectName("lineEdit_Treatment")
        self.gridLayout.addWidget(self.lineEdit_Treatment, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 2)
        self.lineEdit_Address = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.gridLayout.addWidget(self.lineEdit_Address, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        self.lineEdit_Date = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Date.setObjectName("lineEdit_Date")
        self.gridLayout.addWidget(self.lineEdit_Date, 3, 1, 1, 1)
        self.lineEdit_Systemic = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Systemic.setObjectName("lineEdit_Systemic")
        self.gridLayout.addWidget(self.lineEdit_Systemic, 4, 1, 1, 1)
        self.lineEdit_Info = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Info.setObjectName("lineEdit_Info")
        self.gridLayout.addWidget(self.lineEdit_Info, 6, 1, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout.addWidget(self.lineEdit_Name, 0, 1, 1, 1)
        self.lineEdit_Phone = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Phone.setObjectName("lineEdit_Phone")
        self.gridLayout.addWidget(self.lineEdit_Phone, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 3, 1, 1)
        self.lineEdit_Pay = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Pay.setObjectName("lineEdit_Pay")
        self.gridLayout.addWidget(self.lineEdit_Pay, 7, 1, 1, 1)
        self.pushButton_AddPatient = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_AddPatient.setObjectName("pushButton_AddPatient")
        self.gridLayout.addWidget(self.pushButton_AddPatient, 8, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableView.setGeometry(QtCore.QRect(20, 320, 721, 192))
        self.tableView.setObjectName("tableView")
        
        self.pushButton_ShowPAtient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ShowPAtient.setGeometry(QtCore.QRect(760, 390, 141, 41))
        self.pushButton_ShowPAtient.setObjectName("pushButton_ShowPAtient")
        self.pushButton_DeletePatient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeletePatient.setGeometry(QtCore.QRect(760, 440, 141, 41))
        self.pushButton_DeletePatient.setObjectName("pushButton_DeletePatient")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 30, 241, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 221, 81))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 300, 951, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "نرم افزار مدیریت بیماران"))
        self.groupBox.setTitle(_translate("MainWindow", "اطلاعات بیمار"))
        self.label_4.setText(_translate("MainWindow", "وضعیت سیستمیک"))
        self.label_3.setText(_translate("MainWindow", "آدرس"))
        self.label.setText(_translate("MainWindow", "نام بیمار"))
        self.label_5.setText(_translate("MainWindow", "تاریخ"))
        self.label_7.setText(_translate("MainWindow", "توضیحات"))
        self.label_6.setText(_translate("MainWindow", "نوع درمان"))
        self.label_2.setText(_translate("MainWindow", "تلفن"))
        self.label_8.setText(_translate("MainWindow", "هزینه"))
        self.pushButton_AddPatient.setText(_translate("MainWindow", "ثبت"))
        self.pushButton_ShowPAtient.setText(_translate("MainWindow", "نمایش تمامی بیماران"))
        self.pushButton_DeletePatient.setText(_translate("MainWindow", "حذف ردیف انتخاب شده"))
        self.groupBox_2.setTitle(_translate("MainWindow", "جست و جو"))
        self.label_9.setText(_translate("MainWindow", "نام بیمار"))
        self.pushButton.setText(_translate("MainWindow", "نمایش"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
